USE SQL_ASS;
#1
SELECT USER_ID,USERNAME,concat(FIRST_NAME,LAST_NAME)AS FULL_NAME FROM USERS;

#2
SELECT PLAYLIST_NAME, upper(PLAYLIST_NAME)FROM PLAYLISTS;

#3
SELECT *, trim(ITEM_CODE)AS CLEANED_CODE FROM FOOD_ITEMS;


#4
SELECT *, right(IMDB_ID,5)AS IMDB_NO FROM MOVIES;

#5
SELECT*,  replace(SKU_CODE,"-","_")AS SKU_CODE FROM PRODUCTS;

