USE SQL_ASS;

#1
SELECT NAME , RATING 
FROM restaurants
WHERE RATING > 
(SELECT AVG(RATING) FROM RESTAURANTS);

#2
SELECT P1.NAME ,
(SELECT AVG(P2.PRICE)FROM PRODUCTS P2
WHERE P1.CATEGORY= P2.CATEGORY)AS AVG_PRICE
FROM PRODUCTS P1;

#3

SELECT  U.USERNAME ,PL.PLAYLIST_COUNT FROM USERS U 
JOIN  
     ( SELECT USER_ID, 
     COUNT(*) AS PLAYLIST_COUNT 
     FROM PLAYLIST 
     GROUP BY USER_ID) PL
ON U.USER_ID = PL.USER_ID
WHERE PL.PLAYLIST_COUNT >
 (
       SELECT AVG(PLAYLIST_COUNT)
FROM 
            ( SELECT USER_ID, 
			 COUNT(*) AS PLAYLIST_COUNT 
			 FROM PLAYLIST 
             GROUP BY USER_ID
             ) AVG_COUNT
);


#4
SELECT distinct USER_ID FROM ORDERS
WHERE ORDER_AMOUNT > (SELECT AVG(ORDER_AMOUNT)
 FROM ORDERS);



