USE SQL_ASS;

#1
SELECT *FROM restaurants
WHERE RATING>=4.5;

#2
SELECT *FROM MOVIES
WHERE GENRE="ACTION" AND RELEASE_YEAR>2020;

#3
SELECT*FROM PRODUCTS
WHERE CATEGORY NOT IN ("ELECTRONICS") or PRICE<500;

#4
SELECT*FROM USERS
WHERE CITY NOT IN("AHMEDABAD")AND FOLLOWERS>1000;